import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BottomNav } from "@/components/common/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-bg-base text-text-primary antialiased pb-28">
        {/* pb-28: 하단 네비게이션에 콘텐츠가 가려지지 않도록 여백 추가 */}
        <main className="max-w-7xl mx-auto">{children}</main>

        {/* 하단 네비게이션 바 */}
        <BottomNav />
      </body>
    </html>
  );
}
